version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: sbd2_vehicle
      POSTGRES_PASSWORD: sbd2_vehicle
      POSTGRES_DB: sbd2_vehicle
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sbd_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  sbd_network:
    driver: bridge
