version: "3.9"

services:
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-spark
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=sbd1
      - POSTGRES_USER=sbd1
      - POSTGRES_PASSWORD=sbd1
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"

  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: sbd1
      POSTGRES_PASSWORD: sbd1
      POSTGRES_DB: sbd1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
